# Change these first
owner: enyone # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Live Results
    url: https://chrono.live
  - name: Customer support portal
    url: https://support.enymind.fi
  - name: Web site
    url: http://www.enymind.com
  - name: Chrono Cloud 2
    url: $HEARTBEAT_URL

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: up.enymind.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.enymind.com/public/images/enymind_logo_bare_64.png
  name: System status
  introTitle: Enymind system status
  introMessage: See below the operational status of our systems.
  navbar:
    - title: System status
      href: /
    - title: Enymind
      href: http://www.enymind.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
